# Generated by Django 6.0.5 on 2026-05-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('user_message', models.TextField(verbose_name='Сообщение пользователя')),
                ('bot_response', models.TextField(verbose_name='Ответ бота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'История сообщений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('python', 'Python'), ('math', 'Математика'), ('general', 'Общие знания')], max_length=50, verbose_name='Категория')),
                ('question_text', models.TextField(verbose_name='Вопрос')),
                ('correct_answer', models.CharField(max_length=200, verbose_name='Правильный ответ')),
                ('option_a', models.CharField(max_length=200, verbose_name='Вариант A')),
                ('option_b', models.CharField(max_length=200, verbose_name='Вариант B')),
                ('option_c', models.CharField(max_length=200, verbose_name='Вариант C')),
                ('option_d', models.CharField(max_length=200, verbose_name='Вариант D')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
